---
name: cmpsc-100-week-0-day-1
break: true
indent: 4
---

0_week-0-worksheet-data-types-booleans.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "print(cats > dogs)" --count 1 --exact
    MatchFileFragment --fragment "print(gators <= snakes)" --count 1 --exact
    MatchFileFragment --fragment "print(gators < dogs)" --count 1 --exact
    MatchFileFragment --fragment "print(cats == snakes)" --count 1 --exact
    MatchFileFragment --fragment "print(gators != dogs)" --count 1 --exact
    MatchFileFragment --fragment "result = switch_a and switch_b" --count 2 --exact
    MatchFileFragment --fragment "result = switch_d or switch_c" --count 1 --exact
    MatchFileFragment --fragment "result = switch_a and switch_b or switch_d" --count 1 --exact
    MatchFileFragment --fragment "result = not switch_c and switch_b" --count 1 --exact
   
1_week-0-worksheet-lists.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "The basket has 4 items" --count 1 --exact
    MatchFileFragment --fragment "The store_items list has 0 items" --count 1 --exact
    MatchFileFragment --fragment "store_items = [" --count 1 --exact
    MatchFileFragment --fragment "store_items.index(" --count 5
    MatchFileFragment --fragment "basket.index(" --count 1
    MatchFileFragment --fragment "store_items.remove(" --count 5
    
2_week-0-worksheet-slices-tuples.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "(-6, -5, -4, -3, -2, -1, 0)" --count 1 --exact
    MatchFileFragment --fragment "(-8, -6, -4, -2, 0, 2, 4, 6, 8)" --count 1 --exact
    MatchFileFragment --fragment "(-9, -7, -5, -3, -1, 1, 3, 5, 7, 9)" --count 1 --exact
    MatchFileFragment --fragment "(9, 8, 7, 6, 5, 4, 3, 2, 1, 0, -1, -2, -3, -4, -5, -6, -7, -8, -9)" --count 1 --exact
    MatchFileFragment --fragment "(9, 6, 3, 0, -3, -6, -9)" --count 1 --exact
    MatchFileFragment --fragment "print(integers[-1])" --count 1 --exact

3_week-0-worksheet-if-statements.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact

f1_week-0-worksheet-puzzle-box.py:
    ConfirmFileExists
    MatchFileFragment --fragment "[True, False, True]" --count 1 --exact
    MatchFileFragment --fragment "if result == 5" --count 1 --exact
    MatchFileFragment --fragment "print(message)" --count 1 --exact

writing/reflection.md:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountFileWords --count 350
    CountFileParagraphs --count 5

MatchCommandFragment --command "python3 f1_week-0-worksheet-puzzle-box.py" --fragment "🎉🎉🎉You've opened the puzzle box!🎉🎉🎉" --count 1 --exact
